# 1. Thông tin kết nối MySQL
# Lưu ý: Thay 'password_cua_ban' bằng mật khẩu đúng bạn dùng để đăng nhập MySQL Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/mai_linh_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=131105
server.port=9090
# 2. Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
